export const FETCH_BUILDS_START = 'FETCH_BUILDS_START';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';
export const FETCH_BUILDS_ERROR = 'FETCH_BUILDS_ERROR';

export const SET_SETTINGS = 'SET_SETTINGS';

export const RUN_BUILD_START = 'RUN_BUILD_START';
export const RUN_BUILD_SUCCESS = 'RUN_BUILD_SUCCESS';
export const RUN_BUILD_ERROR = 'RUN_BUILD_ERROR';
