export const LINKS = [
	{
		title: 'Support',
		to: '#',
	},
	{
		title: 'Learning',
		to: '#',
	},
	{
		title: 'Русская версия',
		to: '#',
	},
];

export const BUILDS = [
	{
		status: 'fail',
		date: new Date(),
		number: 1234,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'done',
		date: new Date(),
		number: 1233,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '5 ч 30 мин',
	},
	{
		status: 'wait',
		date: new Date(),
		number: 1232,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '2 ч 30 мин',
	},
	{
		status: 'fail',
		date: new Date(),
		number: 1231,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'done',
		date: new Date(),
		number: 1230,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'wait',
		date: new Date(),
		number: 1229,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '2 ч 30 мин',
	},
	{
		status: 'fail',
		date: new Date(),
		number: 1228,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'done',
		date: new Date(),
		number: 1227,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'wait',
		date: new Date(),
		number: 1226,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 30 мин',
	},
	{
		status: 'fail',
		date: new Date(),
		number: 1225,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '6 ч 10 мин',
	},
	{
		status: 'done',
		date: new Date(),
		number: 1224,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'f2f5g5',
		author: 'Philip Kirkorov',
		duration: '1 ч 10 мин',
	},
	{
		status: 'wait',
		date: new Date(),
		number: 1223,
		message: 'Add something interesting',
		branch: 'master',
		hash: 'j4h3g5',
		author: 'Philip Kirkorov',
		duration: '2 ч 30 мин',
	},
];
